%{
    #include <string.h>
    #include "nutshell.tab.hpp"
%}

%option noyywrap

%%

"bye"               { return EXIT; }
[\<\>\|]            { return yytext[0]; }    
\"(\\.|[^"\\])*\"   { yylval.str = strdup(yytext); return WORD; }
[^ &<>\|\\\"\n\t]+  { yylval.str = strdup(yytext); return WORD; }
[\n]                { return STOP; }
<<EOF>>             { return 0; }
[ \t]+              { }
.                   { cout << "Unrecognized token starting with " << yytext[0] << endl; }

%%